name: SQANTI3_aptars
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - biopython>=1.79,<1.80
  - bioconductor-genomeinfodbdata
  - bioconductor-noiseq
  - bioconductor-rtracklayer
  - bcbiogff
  - bedtools
  - bx-python
  - cdna_cupcake=22.0.0
  - desalt
  - gffread
  - gmap
  - isoseq3==4.0.0 #from 3.4.0
  - kallisto
  - lima==2.13.0
  - minimap2==2.17
  - numpy
  - openssl
  - pandoc
  - pbccs==5.0.0
  - perl
  - psutil
  - pybedtools
  - pysam
  - python>=3.7.6,<3.8
  - r-base=4.0.3
  - r-biocmanager
  - r-dplyr
  - r-ggplot2
  - r-ggplotify
  - r-gridbase
  - r-gridextra
  - r-htmltools
  - r-plotly
  - r-plyr
  - r-rmarkdown
  - r-scales
  - r-stringi
  - r-dt
  - r-tidyverse
  - samtools==1.10
  - scipy
  - snakemake==5.32.2
  - star
  - slamem
  - pip:
    - ultra-bioinformatics
